version: 2.1

jobs:
  build_and_publish: 
    docker:
    - image: cimg/base:2024.11
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    steps:
      - checkout # checkout source code
      - setup_remote_docker:
        docker_layer_caching: true # needed to run dind
      - run:
          name: Build
          command: docker build . -t simple-node-circleci
      - run:
          name: Tag
          command: docker tag simple-node-circleci ${DOCKER_USERNAME}/simple-node-circleci
      - run:
          name: Publish
          command: |
            docker push ${DOCKER_USERNAME}/simple-node-gha
workflows:
  build_publish_deploy:
    jobs:
      - build_and_publish