# Simple GHA Work flow

on:
  push:
    branches:
    - main
    paths-ignore:
    - '.circleci/config.yml'
    
jobs:
  build-docker:
    name: Build and Publish a Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build
      run: docker build . -t simple-node-gha

    - name: Tag
      run: docker tag simple-node-gha ${{ secrets.DOCKER_USERNAME }}/simple-node-gha:latest

    - name: Publish
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/simple-node-gha
